### ISSUE TITLE
[REQUEST] Adding Plugins (jellyfin-ani-sync and jellyfin-plugin-subtitleextract)

### ISSUE THREAD

**Issue by Middlepepper** [awesome-jellyfin/awesome-jellyfin#12]
### Project Website

https://github.com/vosmiic/jellyfin-ani-sync
https://github.com/jellyfin/jellyfin-plugin-subtitleextract

### Project Description

[🧩 Plugins](https://github.com/awesome-jellyfin/awesome-jellyfin#-plugins)

- [jellyfin-ani-sync](https://github.com/vosmiic/jellyfin-ani-sync) - A scrobbler and playback sync tool.
- [jellyfin-plugin-subtitleextract](https://github.com/jellyfin/jellyfin-plugin-subtitleextract) - A Plugin to automatically extract embedded subtitles.

**Comment by darmiel** [comment]
Thanks for your suggestion! I have added `jellyfin-ani-sync` (per #13) to the list. I didn`t add `jellyfin-plugin-subtitleextract` for now, as this is an official plugin and already shows up in Jellyfin under "Plugins".
