### ISSUE TITLE
[REQUEST] Jelly-Clipper

### ISSUE THREAD

**Issue by arnolicious** [awesome-jellyfin/awesome-jellyfin#125]
### Project Website

https://github.com/arnolicious/jelly-clipper

### Project Description

Companion project to jellyfin that allows for the creation and sharing of clips made from jellyfin media.
It's also definitely in very early stages.

(If it's not ok to suggest a personal project, feel free to close the issue :D )

**Comment by darmiel** [comment]
I really like this idea!
