### ISSUE TITLE
[BUG] Testflight Icon too big

### ISSUE THREAD

**Issue by UdonCodes** [awesome-jellyfin/awesome-jellyfin#30]
### What's the problem?

The Testflight icon is too big and breaks the table sizeing
![testflight](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/41b3d6b2-d7e0-4663-8d09-12cf1addef66)

### Where's the problem?

https://github.com/awesome-jellyfin/awesome-jellyfin/blob/main/assets/clients/icons/testflight.png

**Comment by UdonCodes** [comment]
Also how about some icons or banners with matching sizes like these:
![googleplay](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/6102d2da-8037-4635-94ef-da7f856573a2)
![testflight](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/2d8053bb-ebb6-4af7-9a10-b19c81e07132)
![fdroid](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/1468bb6a-e649-4977-b90f-c4d18b98a95c)
![appstore](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/645aca12-cbdd-46a9-951b-9ddc4bffcb3f)
![izzisoft](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/68328913-6f43-48e4-8d65-891ee86b4bba)
![amazon](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/ac3b8f23-eb09-4b60-9b93-c2b895ea6930)
![flathub](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/5534fcef-c73b-4218-9af9-95e0dba3b63f)
![github](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/c6f28bc9-f030-4474-be99-fc6e751e7495)
![docker](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/3e95a751-e6ea-4b26-936b-82513e460208)
![demo](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/8e2fe723-5d17-4ed1-8ec7-ecbd9c2b1cd4)
![openrepos](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/2e8b81d5-1437-4939-bcc3-857af5f45466)

**Comment by darmiel** [comment]
Oh, that would be nice, I think they just need to be a bit smaller

**Comment by UdonCodes** [comment]
How about this size ?
![googleplay](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/fcfd2236-69a4-46de-9c78-9dc3cca14ef9)
![testflight](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/21eb7bf9-14c5-4ba9-b759-55f37079cb8d)
![fdroid](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/ff67f069-2854-48ff-aee8-83b6b49d5be4)
![appstore](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/e4f49634-2ade-4ac9-b1a2-f48d787fb422)
![izzisoft](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/c4d8ddea-5bf2-4ca4-a2f9-f92411e3aa3a)
![amazon](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/f18fb39c-a09f-4ecf-aa3e-f8b69b0db1f8)
![flathub](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/6e7ba29b-e42f-4bba-9aeb-a439c9827f94)
![github](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/bff99eee-10d3-422b-ac9a-f1777fd5cfab)
![docker](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/12e40c02-9b19-4f65-b4dc-40b91a54ee16)
![demo](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/b4015762-4c9c-4b99-839f-1c3c7332e6e6)
![openrepos](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/a59314d3-ceb5-44be-a949-71abed5c2ef7)

**Comment by darmiel** [comment]
Yes, that looks good 👍🏻, would you like to create a pull request for it?

**Comment by UdonCodes** [comment]
Sure no problem, I'll make one tomorrow
