### ISSUE TITLE
[BUG] White outline in the banner

### ISSUE THREAD

**Issue by UdonCodes** [awesome-jellyfin/awesome-jellyfin#6]
### What's the problem?

I noticed some white outlines in the README.md displayed banner, so I designed some [banners](https://codeberg.org/Udon/AJ-Banner) that could fix this issue.

Let me know if you like one.

Greetings,
Udon

![AJ-01](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/c7db0e73-7557-46c9-bf4e-1929363e2efa)
![AJ-02](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/faba7a7e-7abe-49be-b5ec-c8872a8d3b98)
![AJ-03](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/49b75376-efba-4998-980c-be151b720f44)
![AJ-04](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/7f0c1f02-c017-47bc-bf1a-2900c02419fd)
![AJ-05](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/df6ac647-543b-4d88-9135-f97ab12e0379)
![AJ-06](https://github.com/awesome-jellyfin/awesome-jellyfin/assets/143291288/e19697a4-2875-4943-b87b-8a18d3e903ac)

### Where's the problem?

2

**Comment by TomRomeo** [comment]
Hey!
Very nice, we didn't even catch that!
It would be great if you could open a PR for that and change out the current banner for the first option.
But please export the image in a higher resolution. :)

**Comment by darmiel** [comment]
Closed with #10
