### ISSUE TITLE
[REQUEST] Outdated Label

### ISSUE THREAD

**Issue by gerba102** [awesome-jellyfin/awesome-jellyfin#8]
I see some projects haven't been updated for a while now so I thought we can add label for outdated projects as we have with 

> Early Release / BETA software  🔸

Or

> Closed-Source Software 📛

I thought something like this 

 `Outdated 📅`

**Comment by darmiel** [comment]
Sounds good, I think "Stale" would be a bit more fitting. What do you think?

**Comment by gerba102** [comment]
That sounds even better 👍

**Comment by darmiel** [comment]
Added stale label for `jellyfin-plugin-skin-manager` and `AnilistSync`. 
Feel free to write here if you find any other outdated/stale projects :)
